# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure('2') do |config|
# general config for all machines

  config.vm.box = 'generic/ubuntu1804'
  config.vm.box_check_update = false
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.inventory_path = "./hosts"
    ansible.compatibility_mode = "2.0"
  end

  config.vm.provider 'libvirt' do |libvirt|
    libvirt.memory = 2048
    libvirt.cpus = 2
  end

# configure all needed vms:

  config.vm.define "samba" do |samba|
    samba.vm.hostname = "samba"
    samba.vm.network 'private_network', ip: '192.168.56.101'
  end

  config.vm.define "nfs" do |nfs|
    nfs.vm.hostname = "nfs"
    nfs.vm.network 'private_network', ip: '192.168.56.102'
  end

end
