# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
# general config for all machines

  config.vm.box = 'ubuntu/focal64'
  config.vm.provision "ansible_local", playbook: "playbook.yml"
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 4096
    vb.cpus = 2
  end

# configure all needed vms:

  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"
    vm1.vm.network 'private_network', ip: '192.168.56.101'
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "vm2"
    vm2.vm.network 'private_network', ip: '192.168.56.102'
  end

  config.vm.define "vm3" do |vm3|
    vm3.vm.hostname = "vm3"
    vm3.vm.network 'private_network', ip: '192.168.56.103'
  end
end
