- hosts: all
  become: true
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Update apt and install samba, smbclient, and winbind
      apt:
        pkg:
          - samba
          - smbclient
          - winbind
        state: latest
        update_cache: true

- hosts: all
  become: true
  tasks:
    - name: Edit /etc/hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
        state: present
      loop: "{{ ansible_play_hosts_all }}"